[tool.poetry]
name = "docurator"
version = "0.1.0"
description = "Decorator for docs retrieval."
authors = ["Iver Schei Noerve <iver@noerve.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
